program: train.py
method: bayes 
metric:
  name: val_loss
  goal: minimize
parameters:
  epochs:
    values: [5, 10]
  num_layers:
    values: [3, 4, 5]
  hidden_size:
    values: [32, 64, 128]
  weight_decay:
    values: [0, 0.0005, 0.5]
  learning_rate:
    values: [1e-3, 1e-4]
  optimizer:
    values: ["sgd", "momentum", "nag", "rmsprop"]
  batch_size:
    values: [16, 32, 64]
  weight_init:
    values: ["random", "Xavier"]
  activation:
    values: ["sigmoid", "tanh", "ReLU"]
