wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
beta1:
  value: 0.5
beta2:
  value: 0.999
epochs:
  value: 20
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
