wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
beta1:
  value: 0.9
beta2:
  value: 0.5
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
