wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.001
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: random
