wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
