wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
