wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
