wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: random
