wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
