wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
