wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
