wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 30
hidden_size:
  value: 128
learning_rate:
  value: 0.05
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
