wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 15
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: Xavier
