wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
